# Regularized Proximal Descent Based Model Framework

In [10]:
%reload_ext autoreload
%autoreload 2

In [24]:
#Importing Needed Libraries
import framework
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

**Load Your Data**

The framework assumes all pre-processing has been done by the user. Simply load, and split your data as a Pandas DataFrame.

In [29]:
#Load your Data 
#file_path = ''
#data = pd.read_csv(file_path)
#labels = data['']
#samples = data.drop([''], axis = 1)'''

In [25]:
#Load your Data -- Example
file_path = '/Users/nicolascutrona/Downloads/heart.csv'
data = pd.read_csv(file_path)
data = data.drop(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak'], axis = 1)
labels = data['HeartDisease']
samples = data.drop(['HeartDisease'], axis = 1)

In [26]:
#Split your Data
X,y = samples, labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

**Hyper-Paramter Selection**

Select the hyper-parameters for model learning:

*Convergence Constant*: A small pre-defined constant that represents the change in model loss per iteration

*Max Iterations*: Select the number of iterations for the model; few iterations may result in non-convergance

*learning Rate*: Give a predefined Learning Rate (Will implement line search WIP)

*Lambda Term*: Give a specified penalty value (Lambda) for the L1 penalty induced on the class-specific attribute weights (Will implement CV for paramter selection WIP)

In [27]:
#Hpyer Parameter Selections (Current Version)
convergence = 1e-3
max_iterations = 1000
learning_rate = 0.01
lambda_term = 0.01

**MODEL FRAMEWORK OUTPUT**

Run the RPNB Framework as shown below.

The output will contain the following:

*Iteration*: The iteration number of model learning

*Posterior Cache First Sample*: The first sample posterior distribution

*Weight Matrix*: The current weight matrix corresponding to class-specific attributes during model learning

*Gradient Weight Matrix Norm*: The norm of the gradient corresponding to the weight matrix. This should be close to zero as model learning progresses, as we hope to find some minimum

*Model Less*: Model loss with respect to the current iteration

*Converged* Boolean convergence check variable

In [28]:
#Run Model Framework
model = framework.Framework(X_train, y_train, X_test, y_test, max_iterations, convergence, learning_rate, lambda_term)
print("Regularized Naive Bayes Training Accuracy:", model.train_accuracy)
print("Regularized Naive Bayes Testing Accuracy:", model.test_accuracy)

_Computing Model Parameters_...

_Optimizing_...

Iteration: 1
Posterior Cache First Sample: [0.6684198709751686, 0.3315801290248313]
Weight Matrix: [[0.99745986 0.99263815 1.00496463 1.01969811 0.98971045]
 [0.99984184 1.02994966 0.99722434 1.01355745 0.98336476]]
Gradient Weight Matrix Norm: 10.028409
Model Loss: 72.56214137403046
Converged: False
Iteration: 2
Posterior Cache First Sample: [0.7023881839763486, 0.29761181602365133]
Weight Matrix: [[0.99329089 0.9803073  1.00683067 1.03926099 0.97361067]
 [1.00122647 1.06720884 0.99749789 1.03025237 0.96677755]]
Gradient Weight Matrix Norm: 10.056264
Model Loss: 73.18451084409918
Converged: False
Iteration: 3
Posterior Cache First Sample: [0.7498976667113926, 0.25010233328860737]
Weight Matrix: [[0.98620592 0.95946924 1.00296146 1.05767754 0.94829238]
 [1.00535252 1.11529469 1.00338524 1.05226832 0.95215696]]
Gradient Weight Matrix Norm: 10.083064
Model Loss: 74.25850938617855
Converged: False
Iteration: 4
Posterior Cache First Sample: